### ISSUE TITLE
Withdraw error kraken

### ISSUE THREAD

**Issue by ultrazeus** [Jorijn/bitcoin-dca#49]
Running this command on RPI4 results in an error:

docker run --rm -it --env-file=/home/xxx/docker/bitcoin-dca/config/bitcoin-dca.conf jorijn/bitcoin-dca:latest withdraw --all

In KrakenClient.php line 77:
EGeneral:Invalid arguments

**Comment by Jorijn** [comment]
Did you take the minimum withdrawal value into account? For Bitcoin, that's currently: 0.00050 XBT.

**Comment by ultrazeus** [comment]
Just checked, withdrawing 0.00215 XBT pops up the same error:

In KrakenClient.php line 77:
EGeneral:Invalid arguments

**Comment by Jorijn** [comment]
Hi @ultrazeus 

Too bad. Did you triple check the withdraw description configured in the .env file that is exactly matches the one added to the Kraken website?

**Comment by ultrazeus** [comment]
Great, that was the glitch. I couldn't make up that this was actually required as it states "This option overrides any configured withdrawal address", assuming that the address I added in the .env file was enough.
The withdrawal was successful, but it did generate a php error:

`PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Jorijn\Bitcoin\Dca\EventListener\XPubAddressUsedListener::__construct() must be an instance of Jorijn\Bitcoin\Dca\Component\AddressFromMasterPublicKeyComponent, instance of Jorijn\Bitcoin\Dca\Component\ExternalAddressFromMasterPublicKeyComponent given, called in /app/var/cache/container.php on line 331 and defined in /app/src/EventListener/XPubAddressUsedListener.php:19
Stack trace:
#0 /app/var/cache/container.php(331): Jorijn\Bitcoin\Dca\EventListener\XPubAddressUsedListener->__construct()
#1 /app/var/cache/container.php(134): BitcoinDcaContainer->getEventListener_XpubAddressUsedService()
#2 /app/vendor/symfony/event-dispatcher/EventDispatcher.php(267): BitcoinDcaContainer->{closure}()
#3 /app/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}()
#4 /app/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callList in /app/src/EventListener/XPubAddressUsedListener.php on line 19`

**Comment by Jorijn** [comment]
Thanks! Great that it worked out. I'll leave this ticket open to serve as a work item to clarify the documentation and figure out what caused the given error.
